blog/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    # auth
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.instant_logout, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    # profile
    path("profile/", views.profile, name="profile"),
    path("update-email/", views.update_email, name="update_email"),
]

blog/devmode/urls.py
from django.urls import path

from . import views

app_name = "devmode"
urlpatterns = [
    path("spylog/", views.spylog, name="spylog"),
]

blog/urls.py
from django.urls import include, path, re_path

import blog.views

app_name = "blog"
urlpatterns = [
    # post views
    re_path(
        # NOTE: if using regex, don't forget ^ to match from the begining
        # isn't strictly possible now, but I left it here just as an example
        "^$|^index/",
        blog.views.index,
        name="index",
    ),
    path("handle_post/", blog.views.PostView.as_view(), name="handle_post"),
    # comment views
    path("<int:post_id>/", blog.views.detail, name="detail"),
    path(
        "<int:post_id>/handle_comment/",
        blog.views.CommentView.as_view(),
        name="handle_comment",
    ),
    # auth
    path("accounts/", include("blog.accounts.urls")),
    # notifications
    path("notifications/", include("blog.notifications.urls")),
    # export/import
    path("management/", include("blog.management.urls")),
    # misc
    path("devmode/", include("blog.devmode.urls")),
]

mysite/urls.py
try:
    from debug_toolbar.toolbar import debug_toolbar_urls  # type: ignore
except ImportError:
    debug_toolbar_urls = lambda: []


from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("blog.urls")),
    path("admin/", admin.site.urls),
    *debug_toolbar_urls(),
]

blog/accounts/forms.py
from django import forms


class UpdateEmailForm(forms.Form):
    # NOTE:
    # Emails aren't unique in Django by default.
    #
    # To change this, we'd need to use custom User model, which we don't do
    # at the moment.
    #
    # If we would want to make them truly unique, we'd need to do that in a
    # model in the first place, because any validation here would be subject
    # to race conditions.
    email = forms.EmailField()

blog/forms.py
from django import forms

from .utils import MAX_COMMENT_LENGTH, MAX_POST_LENGTH


class CommentForm(forms.Form):
    # I wonder how max_length will interact with comment_text's length in db.
    # I wouldn't be surprised if these have different validation logic, at least
    # when it comes to browser behaviour.
    #
    # NOTE: unless you explicitly empty the label,
    # Django will generate it for you.
    comment = forms.CharField(
        widget=forms.Textarea, max_length=MAX_COMMENT_LENGTH, label=""
    )


class PostForm(forms.Form):
    post = forms.CharField(
        widget=forms.Textarea, max_length=MAX_POST_LENGTH, label=""
    )

blog/management/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.files import File
from django.core.validators import FileExtensionValidator


class ExportDataForm(forms.Form):
    download = forms.BooleanField(required=False)


def validate_size(file: File):
    # 5 megabytes
    MAX_SIZE = 5 * 1024 * 1024
    if file.size > MAX_SIZE:
        size_in_mb = file.size / (1024**2)
        max_size_in_mb = MAX_SIZE / (1024**2)
        raise ValidationError(
            f"File size {size_in_mb:.1f}MB > {max_size_in_mb:.1f}MB",
            code="file_size_exceeded",
        )


class ImportDataForm(forms.Form):
    # NOTE: files don't go to cleaned data, so you can't really run form
    # validation in this case.
    # You can do field validation, thankfully.
    data_file = forms.FileField(
        validators=[
            FileExtensionValidator(allowed_extensions=["json"]),
            validate_size,
        ]
    )

blog/notifications/forms.py
from django import forms

from .models import Subscription


class SubscribeForm(forms.ModelForm):
    class Meta:
        model = Subscription
        fields = ["to_new_posts", "to_engaged_posts"]
        labels = {
            "to_new_posts": "Subscribe to new posts",
            "to_engaged_posts": "Subscribe to updates on engaged posts",
        }

blog/accounts/views.py
import logging

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_not_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView as DjangoLoginView
from django.http import (
    HttpRequest,
    HttpResponse,
)
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.views.generic.edit import FormView

from .forms import UpdateEmailForm

logger = logging.getLogger(__name__)


class LoginView(DjangoLoginView):
    template_name = "blog/login.html"
    # if can't figure out the next page, redirect to home
    #
    # NOTE: can't use reverse() here, because it will lead to circular imports
    next_page = reverse_lazy("blog:index")


# NOTE: that must be POST method, not GET
#
# While it's easy to make it a GET request and fire via the link, GET shouldn't
# be used for that.
#
# GET is considered a "safe" method and omits a lot of security checks, but
# logout is a bit of a destructive operation, so yeah...
#
# And because we can't use GET and I don't want to have a separate logout page,
# because that'd be super annoying I have two options
# 1) wrap it in the invisible form
# 2) make a button and place a JS fetch on it
#
# And I went with the third option, HTMX, because why not?
#
# So, HTMX has its own set of quirks.
# 1) One of the points of HTMX are partial updates via template fragments.
# I.e. instead of sending whole HTML document, we only send required part.
#
# Which is cool, but would require to potentially refactor my whole template
# folder, and I don't want to do that, so I just won't do that.
#
# 2) If we're not going to send partial updates, we would keep plain redirects
# but for some reason HTMX doesn't recognise them.
#
# It does have the ability to do that via the custom header, so that's what
# we're using.
#
# P. S. I might re-design my templates later into using fragments.
# Django should allow that with their {% include "other.html" %} directive.
@require_POST
def instant_logout(request: HttpRequest) -> HttpResponse:
    logout(request)

    response = HttpResponse()
    response.headers["HX-Redirect"] = reverse("blog:index")
    return response


# NOTE:
# We use method decorator on "dispatch" because that's an entry point.
#
# << source code explanation >>
# Judging by the code, as_view() copies attributes from `dispatch` method
# to the resulting callable.
# On of such attributes is "login_required" which can be True or False, which
# is then checked by LoginRequiredMiddleware, if such exists, of course.
# login_not_required() decorator sets this attribute to False, but by default
# LoginRequireMiddleware
# << end of source code explanation >>
#
# That's a neat hack, I must say.
@method_decorator(login_not_required, name="dispatch")
class SignUpView(FormView):
    template_name = "blog/signup.html"
    form_class = UserCreationForm
    success_url = reverse_lazy("blog:index")

    def form_valid(self, form):
        # else, register the user
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password1"]

        user = User.objects.create_user(username, None, password)
        user.save()

        # this should always pass, after all, we have just created this user
        logged_user = authenticate(username=username, password=password)
        assert logged_user is not None

        # for convenience sake, log in the user right there
        login(self.request, logged_user)

        return super().form_valid(form)


def profile(request: HttpRequest) -> HttpResponse:
    email_form = UpdateEmailForm()
    return render(request, "blog/profile.html", {"email_form": email_form})


@require_POST
def update_email(request: HttpRequest) -> HttpResponse:
    # assert mainly to convince `mypy`, but also as a safety net
    # we're using LoginNotRequiredMiddleware anyway
    assert request.user.is_authenticated

    form = UpdateEmailForm(request.POST)
    if not form.is_valid():
        return render(
            request,
            "blog/email_form_fragment.html",
            {
                "form": form,
            },
        )
    user = request.user
    # NOTE: ideally we'd send confirmation email here, but it's ... fine for now
    # It's not an outright security vulnerability, probably.
    user.email = form.cleaned_data["email"]
    user.save()

    response = HttpResponse()
    response.headers["HX-Redirect"] = reverse("blog:accounts:profile")
    return response

blog/debug/views.py
import os

from django.conf import settings
from django.contrib.auth.decorators import login_not_required
from django.http import (
    HttpResponse,
)
from django.shortcuts import render


# TODO: require admin perms
@login_not_required
def debug_view(request) -> HttpResponse:
    # NOTE: idk where we should block requests here or in urlconfig?
    #
    # but it's not like this whole view follows any kind of best practices,
    # so should I care about it that much?
    #
    # I should probably use something like sentry for such purpose, but
    # well, it's a pet project
    #
    # and my pet is still a puppy
    #
    # meanwhile, it works okey-ish
    if os.environ.get("DEVMODE") is None:
        return HttpResponse(
            "sommry, debug view is not enabled, go back", status=403
        )

    with open(settings.DEBUG_LOGFILE) as f:
        return render(
            request,
            "blog/debug_view.html",
            # TODO: what if we could reverse it somehow?
            # that would suck with multiline logs though
            #
            # ok I just found out about datadog, it might be simpler to
            # integrate, at least they provide Docker image
            #
            # and hopefully some webview?
            {"debug_file": settings.DEBUG_LOGFILE, "content": f.read()},
        )

blog/devmode/views.py
import os

from django.conf import settings
from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpResponse
from django.shortcuts import render


@staff_member_required
def spylog(request) -> HttpResponse:
    # NOTE: idk where we should block requests here or in urlconfig?
    #
    # but it's not like this whole view follows any kind of best practices,
    # so should I care about it that much?
    #
    # I should probably use something like sentry for such purpose, but
    # well, it's a pet project
    #
    # and my pet is still a puppy
    #
    # meanwhile, it works okey-ish
    if os.environ.get("DEVMODE") is None:
        return HttpResponse(
            "sommry, debug view is not enabled, go back", status=403
        )

    with open(settings.DEBUG_LOGFILE) as f:
        return render(
            request,
            "blog/debug_view.html",
            # TODO: what if we could reverse it somehow?
            # that would suck with multiline logs though
            #
            # ok I just found out about datadog, it might be simpler to
            # integrate, at least they provide Docker image
            #
            # and hopefully some webview?
            {"debug_file": settings.DEBUG_LOGFILE, "content": f.read()},
        )

blog/management/views.py
import io
import json
import logging
from typing import Any, Optional

from django.contrib.admin.views.decorators import staff_member_required
from django.core.exceptions import ValidationError
from django.http import FileResponse, HttpRequest, HttpResponse
from django.shortcuts import render
from django.views.decorators.http import require_GET, require_POST

from .dataexport import get_all_data
from .dataimport import Data as ImportData
from .dataimport import DataError, FormError, data_from, load_all_data_in
from .forms import ExportDataForm, ImportDataForm

logger = logging.getLogger(__name__)


# Create your views here.
@staff_member_required
def data_console(request: HttpRequest) -> HttpResponse:
    import_form = ImportDataForm()
    export_form = ExportDataForm()
    return render(
        request,
        "blog/data_console.html",
        {
            "import_form": import_form,
            "export_form": export_form,
        },
    )


# NOTE: It's a GET request, but we're safe.
#
# The only case where this might be a problem is if another browser makes
# a fetch request behind the scenes, but CORS policies wouldn't allow that.
#
# - If you just visit this page via browser, that's completely fine, we will
# check authentication and authorization server-side.
# - If you visit this page with something like a `curl`, you simply won't pass
# auth.
@staff_member_required
@require_GET
def download_exported_file(request: HttpRequest) -> HttpResponse | FileResponse:
    # TODO: this should probably have some filtering and stuff, because we're
    # practically loading our whole database into memory at once, but whatever.
    #
    # For now, my blog doesn't have any users except me, really, so it's ok.
    databuff = io.BytesIO()
    data = get_all_data()

    # I couldn't get json output the data into the buffer, mypy was mad at me.
    #
    # It is happy with this code although it's probably less efficient.
    databuff.write(json.dumps(data).encode())
    # NOTE: don't forget to seek to the beginning
    databuff.seek(0)

    return FileResponse(
        databuff,
        as_attachment="download" in request.GET,
        filename="data.json",
    )


@staff_member_required
@require_POST
def handle_import_preview(request: HttpRequest) -> HttpResponse:
    data: Optional[ImportData] = None
    form: Optional[Any] = None

    try:
        data = data_from(request).ok_or_raise()
    except FormError as e:
        form = e.form
    except DataError as e:
        logger.error(e.e.errors())

        form = ImportDataForm(request.POST, request.FILES)
        form.add_error(
            "data_file",
            ValidationError("Unable to parse the file", code="format"),
        )

    return render(
        request,
        "blog/import_preview_fragment.html",
        {
            "data": data,
            "form": form,
        },
    )


@staff_member_required
@require_POST
def handle_import(request: HttpRequest) -> HttpResponse:
    try:
        data = data_from(request).ok_or_raise()
    except FormError as e:
        return HttpResponse(e)
    except DataError:
        return HttpResponse("<p>sommry, something went wrong</p>")

    posts, comments = load_all_data_in(data)
    return HttpResponse(
        "<p>import completed! {} posts, {} comments </p>".format(
            posts, comments
        )
    )

blog/notifications/views.py
import logging

from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.http import require_http_methods

from .forms import SubscribeForm
from .models import Subscription

logger = logging.getLogger(__name__)


# Create your views here.
def handle_settings_update(request: HttpRequest) -> HttpResponse:
    # this page requires auth, plus we're using LoginRequiredMiddleware
    # NOTE: `assert` here is mainly for `mypy`
    assert request.user.is_authenticated

    form = SubscribeForm(request.POST)

    if not form.is_valid():
        return render(
            request,
            "blog/notif_settings.html",
            {
                "form": form,
            },
        )

    user_subs = Subscription.objects.get_or_create(user=request.user)[0]
    user_subs.to_new_posts = form.cleaned_data["to_new_posts"]
    user_subs.to_engaged_posts = form.cleaned_data["to_engaged_posts"]
    # imagine if there was a context-manager that automatically calls save() ...
    #
    # dreams, sweat dreams
    user_subs.save()

    return HttpResponseRedirect(reverse("blog:notifications:settings"))


def settings_page(request: HttpRequest) -> HttpResponse:
    # this page requires auth, plus we're using LoginRequiredMiddleware
    # NOTE: `assert` here is mainly for `mypy`
    assert request.user.is_authenticated

    # pre-populate the form
    user_subs = Subscription.objects.get_or_create(user=request.user)[0]
    form = SubscribeForm(instance=user_subs)

    return render(
        request,
        "blog/notif_settings.html",
        {
            "form": form,
        },
    )


# Should I cave in and just write everything in class-based views?
@require_http_methods(["GET", "POST"])
def settings(request: HttpRequest) -> HttpResponse:
    if request.method == "GET":
        return settings_page(request)
    elif request.method == "POST":
        return handle_settings_update(request)
    else:
        # yes, this is unreachable for now, but I'd like to get an error here
        # if this code changes in some unpredicable way
        raise RuntimeError(f"unreachable, {request.method=}")

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}My Django blog{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    <script
        src="https://unpkg.com/htmx.org@2.0.4"
        integrity="sha384-HGfztofotfshcF7+8n44JQL2oJmowVChPTg48S+jvZoztPfvwD79OC/LTtG6dMp+"
        crossorigin="anonymous">
    </script>
</head>
<body>
    <header>
        <!-- using two divs there to split the flebox into two ends --!>
        <div>
            <a href="{% url 'blog:index' %}"> * Blog</a>
        </div>
        <div>
            {% if user.is_authenticated %}
                <span>Account: </span>
                <a href="{% url 'blog:accounts:profile' %}">{{ user }}</a>
                <button
                    hx-post="{% url 'blog:accounts:logout' %}"
                    hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                >Log out</button>
            {% else %}
                <a href="{% url 'blog:accounts:login' %}">
                    You don't have an account? 👀
                </a>
            {% endif %}
        </div>
    </header>

    <span id="tap"> Webserver error </span>
    {% block content %}{% endblock %}

    <footer>
        <span>
            Made with Django &copy juliancoffee 2024
            {% if dev_mode %}
                <a href="{% url 'blog:devmode:spylog' %}"> 👀 </a>
            {% endif %}
        </span>
    </footer>
    <script>
        document.body.addEventListener('htmx:responseError', function (evt) {
            // Start displaying and launch an animation.
            document.getElementById("tap").className = "hit"
            // NOTE: this can glitch if hit repeatedly, so in theory
            // this should work by adding and then removing multiple elements.
            //
            // But this is simple, yet functional enough.
            // And in normal circumstances, it's even pretty.
            setTimeout(function() {
                // Reset to normal
                document.getElementById("tap").classList.remove("hit")
            }, 1000)
        })
    </script>
</body>
</html>

blog/templates/blog/comment_list_fragment.html
{# for use with htmx, not a full document #}
{% load str_extras %}

<div id="comments">
    {% if comments %}
        <ul>
            {% for comment in comments %}
                <li>
                    <!-- commenter name -->
                    {% if comment.author_username %}
                        [{{ comment.author_username }}]
                    {% else %}
                        [unknown]
                    {% endif %}
                    <!-- comment text itself -->
                    {% if comment.comment_text|is_multiline %}
                        <pre>{{ comment.comment_text }}</pre>
                    {% else %}
                        {{ comment.comment_text }}
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No comments yet 🐾</p>
    {% endif %}

    {% if form.errors %}
        {{ form.errors }}
    {% endif %}

    <form
        class="column-form"
        id="comment-form"
        hx-post="{% url 'blog:handle_comment' post.id %}"
        hx-target="#comments"
    >
        {% csrf_token %}

        {% for field in form %}
            {# move errors to top level #}
            {{ field }}
        {% endfor %}

        <input type="submit" value="Meow!">
    </form>
</div>

blog/templates/blog/data_console.html
{% extends "./base.html" %}

{% block content %}
    <!-- Import widget -->
    {% with form=import_form stage="preview" %}
        {% include "./import_form_fragment.html"%}
    {% endwith %}
    <!-- Export widget -->
    <h1> Export Data </h1>
    <form
        class="list-form"
        action="{% url 'blog:management:download_exported_file' %}"
        method=GET
    >
        {{ export_form }}
        <button>
            Export the data as ".json" file
        </button>
    </form>
{% endblock %}

blog/templates/blog/debug_view.html
{% extends "./base.html" %}

{% block content %}
    <h1>debug_file: {{ debug_file }}</h1>
    <pre>{{ content }}</pre>
{% endblock %}

blog/templates/blog/detail.html
{% extends "./base.html" %}

{% block content %}
<pre>{{ post.post_text }}</pre>
<span>
    <em> Written: {{ post.pub_date }} </em>
<span>


{% include "./comment_list_fragment.html" %}
{% endblock %}

blog/templates/blog/email_form_fragment.html
{# for use with htmx, not a full document #}
<div id="email-form">
    {% if form.errors %}
        {{ form.errors }}
    {% endif %}
    <form
        hx-post="{% url 'blog:accounts:update_email' %}"
        hx-target="#email-form"
    >
        {% csrf_token %}

        {{ form }}

        <input type="submit" value="Update your email">
    </form>
</div>

blog/templates/blog/import_form_fragment.html
{# htmx fragment #}

{% comment %}
Offtopic: handling files is difficult, it turns out.

The biggest difficulty is that you can't really recreate the form, in a usual
way at least, because this will nuke the file you have in your browser.

I'm actually not even sure if this would work in "real" frontend framework, but
HTMX definitely doesn't seem to help here.

The idea was (and still is) to have a multi-stage form, where first you submit
the datafile you want to use for import and have it previewed, and then you
can view the changes and reapply them.

This means that you need to reach out to different endpoints, which we
must somehow encode in our form.

And, unfortunately, we can't change form attribute to change its endpoint, we
need to do it via buttons we can replace with out-of-band swaps.
There might be some magic way you can use with HTMX to do what we want, but
yeah, this sounds simpler.
{% endcomment %}

<h1>Import data</h1>

<div id="import-widget">
    <ul id="import-form-preview"></ul>
    <div id="import-form-error"></div>

    <form
        class="list-form"
        hx-encoding="multipart/form-data"
    >
        {% csrf_token %}
        {{ form }}

        <!--
        The sad truth about putting action here is that we disable browser
        validation.
        But it is what it is.
        -->
        <button
            id="import-submit-button"
            hx-post="{% url 'blog:management:handle_import_preview' %}"
            hx-target="#import-form-preview"
            hx-swap="outerHTML"
        >
            Generate preview
        </button>
    </form>
    <div id="import-form-results"><div>
</div>

blog/templates/blog/import_preview_fragment.html
{# for use with htmx, not a full document #}

{% if form %}
    <div id="import-form-error" hx-swap-oob="innerHTML">
        {{ form.errors }}
    </div>
{% else %}
    {# erase errors if valid #}
    <div id="import-form-error" hx-swap-oob="innerHTML"></div>
{% endif %}

<ul id="import-form-preview">
{% for post in data.posts %}
    <li>{{ post.post_text }} <sup>{{ post.pub_date }}</sup>
        <ul>
            {% for comment in post.comments %}
                <li>
                    {{ comment.comment_text }}
                    <sup>[
                        date={{ comment.pub_date }},
                        ip={{ comment.ip }}
                    ]</sup>
                </li>
            {% endfor %}
        </ul>
    </li>
{% endfor %}
</ul>

{# transition to execution stage if ok #}
{% if data %}
<button
    id="import-submit-button"
    hx-swap-oob="outerHTML"
    hx-post="{% url 'blog:management:handle_import' %}"
    hx-target="#import-form-results"
>
    Execute import
</button>
{% endif %}

blog/templates/blog/index.html
{% extends "./base.html" %}

{% block content %}
    {% include "./post_list_fragment.html" %}
{% endblock %}

blog/templates/blog/login.html
{% extends "./base.html" %}

{% block content %}
{% if next %}
    <p>The page you're trying to access requires login.</p>
{% endif %}

<div class="list-form">
    <h1> Login here, if you are friend!</h1>
    <form class="list-form" action="{% url 'blog:accounts:login' %}" method="post">
        {% csrf_token %}

        {{form}}

        <input type="submit" value="Me fren!">
        <!-- that's so that Django knows how to redirect -->
        <input type="hidden" name="next" value="{{ next }}">
    </form>
</div>

<a href="{% url 'blog:accounts:signup' %}">
    <p>We don't know each other yet? Let's fix this!</p>
</a>
{% endblock %}

blog/templates/blog/notif_settings.html
{% extends "./base.html" %}

{% block content %}
<h1>Notification settings</h1>
{% if form.errors %}
    {{ form.errors }}
{% endif %}
<form
    class="list-form"
    action="{% url 'blog:notifications:settings' %}"
    method="POST"
>
    {% csrf_token %}

    {{ form }}

    <input type="submit" value="Update settings">
</form>
<a href="{% url 'blog:accounts:profile' %}">Back to profile page</a>
{% endblock %}

blog/templates/blog/post_list_fragment.html
{# for use with htmx, not a full document #}
{% load str_extras %}

<div id="posts">
    {% if form %}
        <div id="post-form">
            {% if form.errors %}
                {{ form.errors }}
            {% endif %}

            <form
                class='column-form'
                hx-post="{% url 'blog:handle_post' %}"
                hx-target="#posts"
            >
                {% csrf_token %}

                {% for field in form %}
                    {# move errors to top level #}
                    {{ field }}
                {% endfor %}

                <input type="submit" value="Meow!">
            </form>
        </div>
    {% endif %}

    {% if posts %}
        <ul>
            {% for post in posts %}
                <li>
                    {% if post.post_text|is_multiline %}
                        <pre>{{ post.post_text }}</pre>
                        <a href="{% url 'blog:detail' post.id %}">
                            More...
                        </a>
                    {% else %}
                        <a href="{% url 'blog:detail' post.id %}">
                            {{ post.post_text }}
                        </a>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Nothing to see here. Yet 👀<p>
    {% endif %}
</div>

blog/templates/blog/profile.html
{% extends "./base.html" %}
{% load admin_urls %}

{% block content %}
<ul>
    <li>Username: {{ user.username }}</li>
    <li>Last Login: {{ user.last_login }}</li>
    <li>Meowing since: {{ user.date_joined }}</li>
</ul>
<ul>
    <!-- TODO: add a way to enter these -->
    <!-- not like anyone will see it though -->

    <!-- maybe email is sort of important for notifications and stuff? -->
    <li>First Name: {{ user.first_name }}</li>
    <li>Last Name: {{ user.last_name }}</li>
    <li>Email: {{ user.email }}</li>
    {% if user.email %}
    <li>
        <a href="{% url 'blog:notifications:settings' %}">
            Manage notifications
        </a>
    </li>
    {% else %}
    <li>
        Enter email to manage notifications
        {% include "./email_form_fragment.html" with form=email_form %}
    </li>
    {% endif %}
</ul>
<ul>
    <li>Super User: {{ user.is_superuser }}</li>
    {% if user.is_staff %}
    <li>Staff: <a href="{% url 'admin:index' %}">
            Yes, go to the admin page
        </a>
    </li>
    <li>
        Staff: <a href="{% url 'blog:management:data_console' %}">
            Yes, go to the data management page
        </a>
    </li>
    {% else %}
    <li>Staff: Nope</li>
    {% endif %}
    <li>Still with us: {{ user.is_active }}</li>
</ul>
{% endblock %}

blog/templates/blog/signup.html
{% extends "./base.html" %}

{% block content %}
    <h1> Hi here! </h1>

    {% if form.errors %}
        {{ form.errors }}
    {% endif %}
    <form
        action="{% url 'blog:accounts:signup' %}"
        method="POST"
    >
        {% csrf_token %}
        <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password1.label_tag }}</td>
                <td>{{ form.password1 }} </td>
            </tr>
            <tr>
                <td>{{ form.password2.label_tag }}</td>
                <td>{{ form.password2 }}</td>
            </tr>
        </table>
        <input type="submit" value="Yep, that's me">
    </form>
{% endblock %}